// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: reaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ReactionType  string                 `protobuf:"bytes,2,opt,name=reaction_type,json=reactionType,proto3" json:"reaction_type,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_reaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{0}
}

func (x *Reaction) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Reaction) GetReactionType() string {
	if x != nil {
		return x.ReactionType
	}
	return ""
}

func (x *Reaction) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_reaction_proto protoreflect.FileDescriptor

const file_reaction_proto_rawDesc = "" +
	"\n" +
	"\x0ereaction.proto\x12\breaction\x1a\n" +
	"user.proto\"e\n" +
	"\bReaction\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\x12#\n" +
	"\rreaction_type\x18\x02 \x01(\tR\freactionType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05countB$Z\"github.com/Udehlee/tweet-stream/pbb\x06proto3"

var (
	file_reaction_proto_rawDescOnce sync.Once
	file_reaction_proto_rawDescData []byte
)

func file_reaction_proto_rawDescGZIP() []byte {
	file_reaction_proto_rawDescOnce.Do(func() {
		file_reaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reaction_proto_rawDesc), len(file_reaction_proto_rawDesc)))
	})
	return file_reaction_proto_rawDescData
}

var file_reaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reaction_proto_goTypes = []any{
	(*Reaction)(nil), // 0: reaction.Reaction
	(*User)(nil),     // 1: user.User
}
var file_reaction_proto_depIdxs = []int32{
	1, // 0: reaction.Reaction.user:type_name -> user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reaction_proto_init() }
func file_reaction_proto_init() {
	if File_reaction_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reaction_proto_rawDesc), len(file_reaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reaction_proto_goTypes,
		DependencyIndexes: file_reaction_proto_depIdxs,
		MessageInfos:      file_reaction_proto_msgTypes,
	}.Build()
	File_reaction_proto = out.File
	file_reaction_proto_goTypes = nil
	file_reaction_proto_depIdxs = nil
}
