// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: service_tweet_stream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_tweet_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_tweet_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_tweet_stream_proto_rawDescGZIP(), []int{0}
}

var File_service_tweet_stream_proto protoreflect.FileDescriptor

const file_service_tweet_stream_proto_rawDesc = "" +
	"\n" +
	"\x1aservice_tweet_stream.proto\x12\x04grpc\x1a\vtweet.proto\"\a\n" +
	"\x05Empty2:\n" +
	"\vUserService\x12+\n" +
	"\fStreamTweets\x12\v.grpc.Empty\x1a\f.tweet.Tweet0\x01B$Z\"github.com/Udehlee/tweet-stream/pbb\x06proto3"

var (
	file_service_tweet_stream_proto_rawDescOnce sync.Once
	file_service_tweet_stream_proto_rawDescData []byte
)

func file_service_tweet_stream_proto_rawDescGZIP() []byte {
	file_service_tweet_stream_proto_rawDescOnce.Do(func() {
		file_service_tweet_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_tweet_stream_proto_rawDesc), len(file_service_tweet_stream_proto_rawDesc)))
	})
	return file_service_tweet_stream_proto_rawDescData
}

var file_service_tweet_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_tweet_stream_proto_goTypes = []any{
	(*Empty)(nil), // 0: grpc.Empty
	(*Tweet)(nil), // 1: tweet.Tweet
}
var file_service_tweet_stream_proto_depIdxs = []int32{
	0, // 0: grpc.UserService.StreamTweets:input_type -> grpc.Empty
	1, // 1: grpc.UserService.StreamTweets:output_type -> tweet.Tweet
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_tweet_stream_proto_init() }
func file_service_tweet_stream_proto_init() {
	if File_service_tweet_stream_proto != nil {
		return
	}
	file_tweet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_tweet_stream_proto_rawDesc), len(file_service_tweet_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_tweet_stream_proto_goTypes,
		DependencyIndexes: file_service_tweet_stream_proto_depIdxs,
		MessageInfos:      file_service_tweet_stream_proto_msgTypes,
	}.Build()
	File_service_tweet_stream_proto = out.File
	file_service_tweet_stream_proto_goTypes = nil
	file_service_tweet_stream_proto_depIdxs = nil
}
